### ISSUE TITLE
CocoaScript Support

### ISSUE THREAD

**Issue by bomberstudios** [groove25/DrawingKit#1]
Good Morning / Afternoon / Night (depending on your timezone :)!

As you probably know, Sketch will switch its scripting backend from JSTalk to CocoaScript in the upcoming version 3.0.2.

As a result of this change, **some plugins will stop working unless you fix them**.

Guess what? **Yours seems to be one of them**. But worry not! We've identified some of the issues, and the fixes are easy to do (so far :)

Please take a look at the info we've compiled at https://github.com/sketchplugins/cocoascript-migration/, make your changes, and test your scripts with [the latest beta](http://bohemiancoding.com/sketch/beta/). Please don't hesitate to get in touch if you need more help!

Sorry about the extra work, and thank you for your contribution to the amazing Sketch Plugins community :)

Ale M — Bohemian Coding

**Comment by groove25** [comment]
Ale,

Regarding accessing elements in an MSArray, the new syntax doesn't seem backwards-compatible with JSTalk/Sketch 2.

Here's what I used to write: 
    `group.layers()[1];`

Here's the new version:
    `group.layers().array()[1];`

Works great in Sketch 3, but not in Sketch 2. Any suggestions on supporting both versions? (Also, I noticed this wasn't an issue in an earlier implementation of CocoaScript in Beta 7730, released on May 2.)

-Doug D.

**Comment by bomberstudios** [comment]
Let's see...

You can do `group.layers().objectAtIndex(1)`. This works both in Sketch 2 and 3. I'll make sure to update that on the cocoascript-migration repo.

Also: I'm not sure I'm understanding what you mean when you say "this wasn't an issue on 7730". You mean that `group().layers()[1]` worked in 7730?

**Comment by groove25** [comment]
Ah! Using `objectAtIndex()` just occurred to me, too! Thanks for the update.

Yes, in fact, `group().layers()[1]` still does work in 7730. I noticed the release notes for that beta and checked all my scripts against it. They worked fine. It wasn't until I updated to 7779 that I experienced any problems. Please let me know if this turns out to be just a temporary glitch, and I don't actually have to change these lines of code.

I inquired with Gus Mueller about this issue, in case it was something easily fixed; he didn't seem to recognize it as a CocoaScript problem, per se. Since MSArray is particular to Sketch, he couldn't really advise as to why it was broken.

**Comment by bomberstudios** [comment]
Oh, it looks like we actually had _two_ releases numbered 7730: https://rink.hockeyapp.net/apps/0172d48cceec171249a8d850fb16276b and one of them didn't have CocoaScript.

Can you take a look inside the app bundle (right click › Show Package Contents) and see what's in Contents/Frameworks (either CocoaScript.framework or JSTalk.framework)?

**Comment by groove25** [comment]
Believe it or not, I'm using the second 7730 release (on May 2), which claimed to have CocoaScript. But looking in the Frameworks folder, it still just has JSTalk. So that explains the difference there.

**Comment by bomberstudios** [comment]
Good. So that settles the issue, there : ) Shall I close this then?

**Comment by groove25** [comment]
Is there any chance that the MSArray/javascript syntax issue could be fixable on Bohemian's end? It'd be nice to be able to use the same syntax for all array types. (And it sounds as if it's not necessarily a CocoaScript issue?) 

FYI: There's a typo in the Grep search for "integerValue" that causes it not to appear in the results. Also, I found it helpful to add `-e '\[l\]'` to the grep search as I seem to use lowercase L as a variable when "i" is already in use. (I guess I use "l" for layer.)

**Comment by bomberstudios** [comment]
Thanks for the heads up about the typo, I've fixed it already.

As for fixing MSArray on our side... I'll see what I can do : )

**Comment by groove25** [comment]
Going through all my scripts now to make sure they're CocoaScript-friendly… 

Interestingly, I'm not getting any error messages in regards to `integerValue()` and it doesn't prevent my scripts from working.

Something else I learned: You can add `print` to the list of variable names not to use. I got away with it in JSTalk but not in CocoaScript. It makes the application go a bit haywire.

**Comment by bomberstudios** [comment]
Hmm, thanks for double checking that. My scripts were barfing with `integerValue`, but maybe there was an error somewhere else.

As for `print`, yes, it was a reserved word all along. It just looks as if CocoaScript is a bit more strict regarding liberal rewriting of parts of the language : )
